stages:
  - test
  - deploy

variables:
  STAGE_ADMIN_LINK: $STAGE_ADMIN_LINK
  STAGE_ADMIN_EMAIL: $STAGE_ADMIN_EMAIL
  STAGE_ADMIN_PASSWORD: $STAGE_ADMIN_PASSWORD

run_tests:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.47.0-noble
  script:
    - apt-get update
    - apt-get install -y xvfb
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m playwright install --with-deps
    - xvfb-run -a pytest --alluredir=public/reports
    - mkdir -p public
    - allure generate reports/ -o public/allure-report
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - public/allure-report
  when: manual

pages:
  stage: deploy
  script:
    - mv public/allure-report public/
  artifacts:
    paths:
      - public

