stages:
  - test
  - report

variables:
  STAGE_ADMIN_LINK: $STAGE_ADMIN_LINK
  STAGE_ADMIN_EMAIL: $STAGE_ADMIN_EMAIL
  STAGE_ADMIN_PASSWORD: $STAGE_ADMIN_PASSWORD

run_tests:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.47.0-noble
  before_script:
    - apt-get update
    - apt-get install -y xvfb
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m playwright install --with-deps
    - apt-get install -y wget unzip default-jre
    - wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz && tar -zxvf allure-2.25.0.tgz -C /opt/ && ln -s /opt/allure-2.25.0/bin/allure /usr/bin/allure
  script:
    - xvfb-run -a pytest -s -v tests/test_sign_up_flow_dpf.py -k test_sign_up_website_qr_type --alluredir=allure-results
  after_script:
    - allure generate -c allure-results -o allure-report
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - allure-report
  when: manual

pages:
  stage: report
  needs:
    - run_tests
  script:
    - mkdir public
    - cp -r allure-report/* public
  artifacts:
    when: on_success
    expire_in: never
    paths:
      - public

