stages:
  - test
  - deploy

variables:
  STAGE_ADMIN_LINK: $STAGE_ADMIN_LINK
  STAGE_ADMIN_EMAIL: $STAGE_ADMIN_EMAIL
  STAGE_ADMIN_PASSWORD: $STAGE_ADMIN_PASSWORD

run_tests:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.47.0-noble
  before_script:
  - mkdir -p /public/allure-report
  - echo "Содержимое папки перед загрузкой:"
  - ls -la /public allure-report
  script:
    - apt-get update
    - apt-get install -y xvfb
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m playwright install --with-deps
  #  - if [ -d public/reports/history ]; then cp -R public/reports/history public/reports/history_backup; fi
    - xvfb-run -a pytest tests/test_sign_up_flow_default.py --alluredir=reports
  #  - if [ -d public/reports/history_backup ]; then cp -R public/reports/history_backup public/reports/history; fi
    - mkdir -p public
    - allure generate reports/ -o /public/allure-report
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - /public/allure-report
     # - public/reports/history
  when: manual

pages:
  stage: deploy
  needs:
    - job: run_tests
  script:
    - mv /public/allure-report public/
  artifacts:
    paths:
      - /public

