from dotenv import load_dotenv
import os

def get_env(var):
    load_dotenv()
    return os.getenv(var)


languages_urls = {
    "ar": "https://oqg-staging.test-qr.com/ar",
    # "bg": "https://oqg-staging.test-qr.com/bg",
    # "cs": "https://oqg-staging.test-qr.com/cs",
    # "da": "https://oqg-staging.test-qr.com/da",
    "de": "https://oqg-staging.test-qr.com/de",
    "el": "https://oqg-staging.test-qr.com/el",
    "en": "https://oqg-staging.test-qr.com",
    # "es": "https://oqg-staging.test-qr.com/es",
    # "fi": "https://oqg-staging.test-qr.com/fi",
    # "fr": "https://oqg-staging.test-qr.com/fr",
    "he": "https://oqg-staging.test-qr.com/he",
    # "hi": "https://oqg-staging.test-qr.com/hi",
    # "hr": "https://oqg-staging.test-qr.com/hr",
    # "hu": "https://oqg-staging.test-qr.com/hu",
    # "id": "https://oqg-staging.test-qr.com/id",
    # "it": "https://oqg-staging.test-qr.com/it",
    # "ja": "https://oqg-staging.test-qr.com/ja",
    # "ko": "https://oqg-staging.test-qr.com/ko",
    # "ms": "https://oqg-staging.test-qr.com/ms",
    # "nl": "https://oqg-staging.test-qr.com/nl",
    # "no": "https://oqg-staging.test-qr.com/no",
    # "pl": "https://oqg-staging.test-qr.com/pl",
    # "pt": "https://oqg-staging.test-qr.com/pt",
    # "pt-br": "https://oqg-staging.test-qr.com/pt-br",
    # "ro": "https://oqg-staging.test-qr.com/ro",
    # "sk": "https://oqg-staging.test-qr.com/sk",
    # "sl": "https://oqg-staging.test-qr.com/sl",
    # "sr": "https://oqg-staging.test-qr.com/sr",
    # "sv": "https://oqg-staging.test-qr.com/sv",
    # "th": "https://oqg-staging.test-qr.com/th",
    # "tr": "https://oqg-staging.test-qr.com/tr",
    # "uk": "https://oqg-staging.test-qr.com/uk",
    # "zh-cn": "https://oqg-staging.test-qr.com/zh-cn",
    # "zh-hk": "https://oqg-staging.test-qr.com/zh-hk"
}

languages_dpf_urls = {
    "ar": "https://oqg-staging.test-qr.com/ar/create?step=1&qr_onboarding=active_dpf",
    # "bg": "https://oqg-staging.test-qr.com/bg/create?step=1&qr_onboarding=active_dpf",
    # "cs": "https://oqg-staging.test-qr.com/cs/create?step=1&qr_onboarding=active_dpf",
    # "da": "https://oqg-staging.test-qr.com/da/create?step=1&qr_onboarding=active_dpf",
    "de": "https://oqg-staging.test-qr.com/de/create?step=1&qr_onboarding=active_dpf",
    # "el": "https://oqg-staging.test-qr.com/el/create?step=1&qr_onboarding=active_dpf",
    "en": "https://oqg-staging.test-qr.com/create?step=1&qr_onboarding=active_dpf",
    # "es": "https://oqg-staging.test-qr.com/es/create?step=1&qr_onboarding=active_dpf",
    # "fi": "https://oqg-staging.test-qr.com/fi/create?step=1&qr_onboarding=active_dpf",
    "fr": "https://oqg-staging.test-qr.com/fr/create?step=1&qr_onboarding=active_dpf",
    "he": "https://oqg-staging.test-qr.com/he/create?step=1&qr_onboarding=active_dpf",
    # "hi": "https://oqg-staging.test-qr.com/hi/create?step=1&qr_onboarding=active_dpf",
    # "hr": "https://oqg-staging.test-qr.com/hr/create?step=1&qr_onboarding=active_dpf",
    # "hu": "https://oqg-staging.test-qr.com/hu/create?step=1&qr_onboarding=active_dpf",
    # "id": "https://oqg-staging.test-qr.com/id/create?step=1&qr_onboarding=active_dpf",
    # "it": "https://oqg-staging.test-qr.com/it/create?step=1&qr_onboarding=active_dpf",
    # "ja": "https://oqg-staging.test-qr.com/ja/create?step=1&qr_onboarding=active_dpf",
    # "ko": "https://oqg-staging.test-qr.com/ko/create?step=1&qr_onboarding=active_dpf",
    # "ms": "https://oqg-staging.test-qr.com/ms/create?step=1&qr_onboarding=active_dpf",
    # "nl": "https://oqg-staging.test-qr.com/nl/create?step=1&qr_onboarding=active_dpf",
    # "no": "https://oqg-staging.test-qr.com/no/create?step=1&qr_onboarding=active_dpf",
    # "pl": "https://oqg-staging.test-qr.com/pl/create?step=1&qr_onboarding=active_dpf",
    # "pt": "https://oqg-staging.test-qr.com/pt/create?step=1&qr_onboarding=active_dpf",
    # "pt-br": "https://oqg-staging.test-qr.com/pt-br/create?step=1&qr_onboarding=active_dpf",
    # "ro": "https://oqg-staging.test-qr.com/ro/create?step=1&qr_onboarding=active_dpf",
    # "sk": "https://oqg-staging.test-qr.com/sk/create?step=1&qr_onboarding=active_dpf",
    # "sl": "https://oqg-staging.test-qr.com/sl/create?step=1&qr_onboarding=active_dpf",
    # "sr": "https://oqg-staging.test-qr.com/sr/create?step=1&qr_onboarding=active_dpf",
    # "sv": "https://oqg-staging.test-qr.com/sv/create?step=1&qr_onboarding=active_dpf",
    # "th": "https://oqg-staging.test-qr.com/th/create?step=1&qr_onboarding=active_dpf",
    # "tr": "https://oqg-staging.test-qr.com/tr/create?step=1&qr_onboarding=active_dpf",
    # "uk": "https://oqg-staging.test-qr.com/uk/create?step=1&qr_onboarding=active_dpf",
    # "zh-cn": "https://oqg-staging.test-qr.com/zh-cn/create?step=1&qr_onboarding=active_dpf",
    # "zh-hk": "https://oqg-staging.test-qr.com/zh-hk/create?step=1&qr_onboarding=active_dpf"
}

languages_nsf_urls = {
    "ar": "https://oqg-staging.test-qr.com/ar/create?step=1&qr_onboarding=active_nsf",
    # "bg": "https://oqg-staging.test-qr.com/bg/create?step=1&qr_onboarding=active_nsf",
    # "cs": "https://oqg-staging.test-qr.com/cs/create?step=1&qr_onboarding=active_nsf",
    # "da": "https://oqg-staging.test-qr.com/da/create?step=1&qr_onboarding=active_nsf",
    "de": "https://oqg-staging.test-qr.com/de/create?step=1&qr_onboarding=active_nsf",
    # "el": "https://oqg-staging.test-qr.com/el/create?step=1&qr_onboarding=active_nsf",
    "en": "https://oqg-staging.test-qr.com/create?step=1&qr_onboarding=active_nsf",
    # "es": "https://oqg-staging.test-qr.com/es/create?step=1&qr_onboarding=active_nsf",
    # "fi": "https://oqg-staging.test-qr.com/fi/create?step=1&qr_onboarding=active_nsf",
    "fr": "https://oqg-staging.test-qr.com/fr/create?step=1&qr_onboarding=active_nsf",
    "he": "https://oqg-staging.test-qr.com/he/create?step=1&qr_onboarding=active_nsf",
    # "hi": "https://oqg-staging.test-qr.com/hi/create?step=1&qr_onboarding=active_nsf",
    # "hr": "https://oqg-staging.test-qr.com/hr/create?step=1&qr_onboarding=active_nsf",
    # "hu": "https://oqg-staging.test-qr.com/hu/create?step=1&qr_onboarding=active_nsf",
    # "id": "https://oqg-staging.test-qr.com/id/create?step=1&qr_onboarding=active_nsf",
    # "it": "https://oqg-staging.test-qr.com/it/create?step=1&qr_onboarding=active_nsf",
    # "ja": "https://oqg-staging.test-qr.com/ja/create?step=1&qr_onboarding=active_nsf",
    # "ko": "https://oqg-staging.test-qr.com/ko/create?step=1&qr_onboarding=active_nsf",
    # "ms": "https://oqg-staging.test-qr.com/ms/create?step=1&qr_onboarding=active_nsf",
    # "nl": "https://oqg-staging.test-qr.com/nl/create?step=1&qr_onboarding=active_nsf",
    # "no": "https://oqg-staging.test-qr.com/no/create?step=1&qr_onboarding=active_nsf",
    # "pl": "https://oqg-staging.test-qr.com/pl/create?step=1&qr_onboarding=active_nsf",
    # "pt": "https://oqg-staging.test-qr.com/pt/create?step=1&qr_onboarding=active_nsf",
    # "pt-br": "https://oqg-staging.test-qr.com/pt-br/create?step=1&qr_onboarding=active_nsf",
    # "ro": "https://oqg-staging.test-qr.com/ro/create?step=1&qr_onboarding=active_nsf",
    # "sk": "https://oqg-staging.test-qr.com/sk/create?step=1&qr_onboarding=active_nsf",
    # "sl": "https://oqg-staging.test-qr.com/sl/create?step=1&qr_onboarding=active_nsf",
    # "sr": "https://oqg-staging.test-qr.com/sr/create?step=1&qr_onboarding=active_nsf",
    # "sv": "https://oqg-staging.test-qr.com/sv/create?step=1&qr_onboarding=active_nsf",
    # "th": "https://oqg-staging.test-qr.com/th/create?step=1&qr_onboarding=active_nsf",
    # "tr": "https://oqg-staging.test-qr.com/tr/create?step=1&qr_onboarding=active_nsf",
    # "uk": "https://oqg-staging.test-qr.com/uk/create?step=1&qr_onboarding=active_nsf",
    # "zh-cn": "https://oqg-staging.test-qr.com/zh-cn/create?step=1&qr_onboarding=active_nsf",
    # "zh-hk": "https://oqg-staging.test-qr.com/zh-hk/create?step=1&qr_onboarding=active_nsf"
}