version: '3.7'

services:
  ui-tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "ls -la && xvfb-run pytest $TEST_PATH -sv -n auto --alluredir=allure-results && ls -la allure-results"
    working_dir: /app/workspace
    environment:
      BROWSER: "${BROWSER}"
      TEST_PATH: "${TEST_PATH}"
      STAGE_ADMIN_LINK: "${STAGE_ADMIN_LINK}"
      STAGE_ADMIN_EMAIL: "${STAGE_ADMIN_EMAIL}"
      STAGE_ADMIN_PASSWORD: "${STAGE_ADMIN_PASSWORD}"
