version: '3.7'

services:
  chrome-tests:
    image: ui-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/workspace
    command: /bin/sh -c "ls -la && xvfb-run -a pytest tests/test-debug.py -sv -n 20 --alluredir=allure-results"
    working_dir: /app/workspace
    environment:
      BROWSER: "chromium"
      STAGE_ADMIN_LINK: ${STAGE_ADMIN_LINK}
      STAGE_ADMIN_EMAIL: ${STAGE_ADMIN_EMAIL}
      STAGE_ADMIN_PASSWORD: ${STAGE_ADMIN_PASSWORD}

  webkit-tests:
    image: ui-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./:/app/workspace
    command: /bin/sh -c "ls -la && xvfb-run -a pytest tests/test-debug.py -sv -n 20 --alluredir=allure-results"
    working_dir: /app/workspace
    environment:
      BROWSER: "webkit"
      STAGE_ADMIN_LINK: ${STAGE_ADMIN_LINK}
      STAGE_ADMIN_EMAIL: ${STAGE_ADMIN_EMAIL}
      STAGE_ADMIN_PASSWORD: ${STAGE_ADMIN_PASSWORD}

  firefox-tests:
    image: ui-tests:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/workspace
    command: >
      /bin/sh -c "ls -la && 
      xvfb-run -a pytest tests/test-debug.py -sv -n 20 --alluredir=allure-results"
    working_dir: /app/workspace
    environment:
      BROWSER: "firefox"
      STAGE_ADMIN_LINK: ${STAGE_ADMIN_LINK}
      STAGE_ADMIN_EMAIL: ${STAGE_ADMIN_EMAIL}
      STAGE_ADMIN_PASSWORD: ${STAGE_ADMIN_PASSWORD}