version: '3.7'

services:
  ui-tests:
    image: ghcr.io/bohdan-wtl/qr-generator/ui-tests:v5
    volumes:
      - ./:/app/workspace
      - ./allure-results:/app/workspace/allure-results
    command: /bin/sh -c "ls -la && xvfb-run pytest $TEST_PATH -sv -n 4 --alluredir=allure-results && ls -la allure-results"
    working_dir: /app/workspace
    environment:
      BROWSER: "${BROWSER}"
      TEST_PATH: "${TEST_PATH}"
      STAGE_ADMIN_LINK: "${STAGE_ADMIN_LINK}"
      STAGE_ADMIN_EMAIL: "${STAGE_ADMIN_EMAIL}"
      STAGE_ADMIN_PASSWORD: "${STAGE_ADMIN_PASSWORD}"
