version: '3.7'

services:
  ui-tests:
    image: ghcr.io/bohdan-wtl/qr-generator/ui-tests:v3
    command: /bin/sh -c "ls -la && xvfb-run pytest $TEST_PATH -sv -n auto --alluredir=allure-results"
    working_dir: /app/workspace
    environment:
      - BROWSER
      - TEST_PATH
      - STAGE_ADMIN_LINK
      - STAGE_ADMIN_EMAIL
      - STAGE_ADMIN_PASSWORD
