name: Lighthouse Desktop Check
on: workflow_dispatch

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir -p ${{ github.workspace }}/tmp/artifacts

    - name: Lighthouse
      id: lighthouseCheck
      uses: foo-software/lighthouse-check-action@master
      with:
        outputDirectory: ${{ github.workspace }}/tmp/artifacts
        urls: 'https://oqg-staging.test-qr.com/,https://oqg-staging.test-qr.com/register'
        device: 'desktop'

    - name: Verify Lighthouse Check results
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "50"
        minBestPracticesScore: "50"
        minPerformanceScore: "50"
        minSeoScore: "50"

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse Desktop Reports
        path: ${{ github.workspace }}/tmp/artifacts