name: Regression Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Select browser"
        required: true
        default: "chrome"
        type: choice
        options:
          - "chrome"
          - "webkit"
          - "firefox"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      STAGE_ADMIN_LINK: ${{ secrets.STAGE_ADMIN_LINK }}
      STAGE_ADMIN_EMAIL: ${{ secrets.STAGE_ADMIN_EMAIL }}
      STAGE_ADMIN_PASSWORD: ${{ secrets.STAGE_ADMIN_PASSWORD }}
    strategy:
      matrix:
        test_package: [tests_cff_flow, tests_default_flow, tests_dpf_flow, tests_nsf_flow]
    outputs:
      allure-results: ${{ steps.store-results.outputs.allure-results }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Install Docker Compose
        run: |
          sudo apt-get update -y
          sudo apt-get install -y docker-compose

      - name: Run tests
        env:
          TEST_PACKAGE: ${{ matrix.test_package }}
        run: |
          if [ "${{ github.event.inputs.browser }}" == "chrome" ]; then
            docker-compose run -e TEST_PACKAGE=${{ matrix.test_package }} chrome-tests || true
          elif [ "${{ github.event.inputs.browser }}" == "webkit" ]; then
            docker-compose run -e TEST_PACKAGE=${{ matrix.test_package }} webkit-tests || true
          elif [ "${{ github.event.inputs.browser }}" == "firefox" ]; then
            docker-compose run -e TEST_PACKAGE=${{ matrix.test_package }} firefox-tests || true

      - name: Upload Allure results
        id: store-results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.test_package }}
          path: allure-results

  combine-results:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-${{ matrix.test_package }}
          path: allure-results-${{ matrix.test_package }}

      - name: Combine Allure results
        run: |
          mkdir -p combined-allure-results
          cp -R allure-results-*/. combined-allure-results/

      - name: Generate Allure report
        run: |
          allure generate combined-allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          target-folder: ./${{ github.event.inputs.browser }}
          clean: true

      - name: Send notification to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          REPORT_URL="https://qr-generator-${{ github.event.inputs.browser }}.vercel.app/"
          
          curl -X POST -H 'Content-type: application/json' --data '{
          "text": "Tests are finished",
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": ":white_check_mark: @here Tests are finished for *'"${{ github.event.inputs.browser }}"'*. <'"${REPORT_URL}"'|Open link>"
              }
            }
          ]
          }' $SLACK_WEBHOOK_URL
