name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 180
    runs-on: ubuntu-latest
    container:
      image: white779/playwright-python:wtl

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Playwright tests with Xvfb
        env:
          STAGE_ADMIN_LINK: ${{ vars.STAGE_ADMIN_LINK }}
          STAGE_ADMIN_EMAIL: ${{ vars.STAGE_ADMIN_EMAIL }}
          STAGE_ADMIN_PASSWORD: ${{ vars.STAGE_ADMIN_PASSWORD }}
        run: xvfb-run -a pytest tests/

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-reports
          path: reports
