  name: Playwright Tests
  on:
    workflow_dispatch:
      inputs:
        browser:
          description: 'Choose the browser to run tests on (chromium, webkit)'
          required: true
          default: 'chromium'
          type: choice
          options:
            - chromium
            - webkit
            - both

  jobs:
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          browser: [ "chromium", "webkit" ]
        max-parallel: 2

      steps:
        - name: Check out repository
          uses: actions/checkout@v2

        - name: Check out gh-pages branch
          uses: actions/checkout@v2
          with:
            ref: gh-pages
            path: gh-pages

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.12'

        - name: Cache system dependencies and Allure
          uses: actions/cache@v2
          with:
            path: |
              /usr/local/bin/allure
              /opt/allure-2.25.0
            key: ${{ runner.os }}-system-dependencies-allure


        - name: Install dependencies
          if: steps.cache-system-dependencies-and-allure.outputs.cache-hit != 'true'
          run: |
            sudo apt-get update && \
            sudo apt-get install -y wget xvfb default-jre && \
            python -m pip install --upgrade pip && \
            pip install -r requirements.txt && \
            wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz && \
            tar -zxvf allure-2.25.0.tgz -C /opt/ && \
            sudo rm -f /usr/local/bin/allure && \
            sudo ln -s /opt/allure-2.25.0/bin/allure /usr/local/bin/allure && \
            sudo chmod +x /usr/local/bin/allure

        - name: Cache Playwright browsers and pytest-playwright
          uses: actions/cache@v2
          with:
            path: |
              ~/.cache/ms-playwright
              ~/.cache/pip
            key: ${{ runner.os }}-playwright-browsers

        - name: Install Playwright Browsers
          if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
          run: |
            python -m pip install pytest-playwright && \
            playwright install

        - name: Run your tests
          if: ${{ github.event.inputs.browser == 'both' || github.event.inputs.browser == matrix.browser }}
          env:
            BROWSER: ${{ matrix.browser }}
            STAGE_ADMIN_LINK: ${{secrets.STAGE_ADMIN_LINK}}
            STAGE_ADMIN_EMAIL: ${{secrets.STAGE_ADMIN_EMAIL}}
            STAGE_ADMIN_PASSWORD: ${{secrets.STAGE_ADMIN_PASSWORD}}
          run: xvfb-run -a pytest tests/test-debug.py -sv -n 10 --alluredir=allure-results --browser_name=${BROWSER}

        - name: Upload Allure results as artifact
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: allure-results-${{ matrix.browser }}
            path: allure-results

    merge-reports:
      runs-on: ubuntu-latest
      needs: test

      steps:
        - name: Check out repository
          uses: actions/checkout@v2
          with:
            ref: gh-pages
            path: gh-pages

        - name: Download Chrome Allure results artifacts
          if: always() && (github.event.inputs.browser == 'both' || github.event.inputs.browser == 'chromium')

          uses: actions/download-artifact@v2
          with:
            name: allure-results-chromium
            path: allure-results/chromium

        - name: Download WebKit Allure results artifacts
          if: always() && (github.event.inputs.browser == 'both' || github.event.inputs.browser == 'chromium')
          uses: actions/download-artifact@v2
          with:
            name: allure-results-webkit
            path: allure-results/webkit

        - name: Merge Allure results and generate report
          run: |
            mkdir -p gh-pages/allure-results
            if [ -d allure-results/chromium ]; then cp -r allure-results/chromium/* gh-pages/allure-results/; fi
            if [ -d allure-results/webkit ]; then cp -r allure-results/webkit/* gh-pages/allure-results/; fi
            allure generate gh-pages/allure-results -o gh-pages --clean

        - name: Deploy Allure Report to GitHub Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.CI_TOKEN }}
            publish_dir: gh-pages
            keep_files: true
