name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose the browser to run tests on (chromium, webkit)'
        required: true
        default: 'chromium'
        options:
          - chromium
          - webkit

jobs:
  test:
    timeout-minutes: 180
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Setup Docker Compose
        run: |
          docker-compose up --build -d

      - name: Run tests in Docker container
        if: ${{ github.event.inputs.browser == 'chromium' || github.event.inputs.browser == 'webkit' }} # Условие для выбранного браузера
        env:
          BROWSER: ${{ github.event.inputs.browser }}
        run: docker-compose up --exit-code-from regression || true

      - name: Copy history for selected browser from gh-pages to allure-results
        if: ${{ github.event.inputs.browser == 'chromium' || github.event.inputs.browser == 'webkit' }} # Условие для выбранного браузера
        run: |
          sudo mkdir -p allure-results/${{ github.event.inputs.browser }}/history
          if [ -d "./.github/gh-pages/${{ github.event.inputs.browser }}/history" ]; then
            sudo cp -R ./.github/gh-pages/${{ github.event.inputs.browser }}/history/* allure-results/${{ github.event.inputs.browser }}/history/
          fi

      - name: Generate Allure report
        if: ${{ github.event.inputs.browser == 'chromium' || github.event.inputs.browser == 'webkit' }} # Условие для выбранного браузера
        run: |
          sudo docker-compose run regression /bin/sh -c "allure generate allure-results/${{ github.event.inputs.browser }} --clean -o allure-report/${{ github.event.inputs.browser }}"

      - name: Update Allure history for the selected browser
        if: ${{ github.event.inputs.browser == 'chromium' || github.event.inputs.browser == 'webkit' }} # Условие для выбранного браузера
        run: |
          sudo mkdir -p ./.github/gh-pages/${{ github.event.inputs.browser }}/history
          sudo cp -R allure-report/${{ github.event.inputs.browser }}/history/* ./.github/gh-pages/${{ github.event.inputs.browser }}/history/

      - name: Deploy to GitHub Pages
        if: ${{ github.event.inputs.browser == 'chromium' || github.event.inputs.browser == 'webkit' }} # Условие для выбранного браузера
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report/${{ github.event.inputs.browser }}
          clean: false
