name: Docker UI Tests with Deployment

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Select browser"
        required: true
        default: "chrome"
        type: choice
        options:
          - "chrome"
          - "webkit"
          - "firefox"

jobs:
  # Job для запуска тестов и деплоя отчётов
  tests_and_deploy:
    runs-on: ubuntu-latest
    env:
      STAGE_ADMIN_LINK: ${{ secrets.STAGE_ADMIN_LINK }}
      STAGE_ADMIN_EMAIL: ${{ secrets.STAGE_ADMIN_EMAIL }}
      STAGE_ADMIN_PASSWORD: ${{ secrets.STAGE_ADMIN_PASSWORD }}

    steps:
      # Чекаут основной ветки main
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./gh-pages
          clean: true

      # Логин в Docker Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Установка Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update -y
          sudo apt-get install -y docker-compose

      # Запуск тестов для выбранного браузера
      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.browser }}" == "chrome" ]; then
            docker-compose up chrome-tests || true
          elif [ "${{ github.event.inputs.browser }}" == "webkit" ]; then
            docker-compose up webkit-tests || true
          elif [ "${{ github.event.inputs.browser }}" == "firefox" ]; then
            docker-compose up firefox-tests || true
          fi

      - name: Debug current directory and files
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of current directory:"
          ls -la

      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history
          sudo cp -R ./gh-pages/${{ github.event.inputs.browser }}/history/* allure-results/history/

      # Генерация Allure отчёта
      - name: Generate Allure report
        run: |
          docker-compose run ${{ github.event.inputs.browser }}-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"

      # Создание директории для отчётов браузера
      - name: Create directory for browser reports
        run: |
          mkdir -p ./gh-pages/${{ github.event.inputs.browser }}
          echo "Created directory: ./gh-pages/${{ github.event.inputs.browser }}"

      # Копирование отчётов в gh-pages
      - name: Copy Allure report to browser directory
        run: |
          cp -R allure-report/* ./gh-pages/${{ github.event.inputs.browser }}/
          echo "Copied Allure report to ./gh-pages/${{ github.event.inputs.browser }}"

      # Деплой отчётов на gh-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: ./gh-pages/${{ github.event.inputs.browser }}
          target-folder: ./${{ github.event.inputs.browser }}
          clean: true
