name: Docker UI Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Select browser"
        required: true
        default: "chromium"
        type: choice
        options:
          - "chromium"
          - "webkit"
          - "firefox"

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      STAGE_ADMIN_LINK: ${{ secrets.STAGE_ADMIN_LINK }}
      STAGE_ADMIN_EMAIL: ${{ secrets.STAGE_ADMIN_EMAIL }}
      STAGE_ADMIN_PASSWORD: ${{ secrets.STAGE_ADMIN_PASSWORD }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check out gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Check out chrome_reports branch
        uses: actions/checkout@v4
        with:
          ref: chrome_reports
          path: ./.github/chrome_reports

      - name: Check out webkit_reports branch
        uses: actions/checkout@v4
        with:
          ref: webkit_reports
          path: ./.github/webkit_reports

      - name: Check out firefox_reports branch
        uses: actions/checkout@v4
        with:
          ref: firefox_reports
          path: ./.github/firefox_reports

      - name: Set up Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/.docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/bohdan-wtl/qr-generator/ui-tests:v1
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.CI_TOKEN }}


      - name: Run Chrome tests
        if: ${{ github.event.inputs.browser == 'chromium' }}
        run: docker-compose up chrome-tests || true

      - name: Run Webkit tests
        if: ${{ github.event.inputs.browser == 'webkit' }}
        run: docker-compose up webkit-tests || true

      - name: Run Firefox tests
        if: ${{ github.event.inputs.browser == 'firefox' }}
        run: docker-compose up firefox-tests || true

#      - name: Copy history from firefox_reports to allure-results
#        if: ${{ github.event.inputs.browser == 'firefox' }}
#        run: |
#          sudo mkdir -p allure-results/history
#          sudo cp -R ./.github/firefox_reports/history/* allure-results/history/
#
#      - name: Copy history from webkit_reports to allure-results
#        if: ${{ github.event.inputs.browser == 'webkit' }}
#        run: |
#          sudo mkdir -p allure-results/history
#          sudo cp -R ./.github/webkit_reports/history/* allure-results/history/
#
      - name: Copy history from chrome_reports to allure-results
        if: ${{ github.event.inputs.browser == 'chromium' }}
        run: |
          sudo mkdir -p allure-results/history
          sudo cp -R ./.github/chrome_reports/history/* allure-results/history/

      - name: Generate Allure report
        run: |
          if [ "${{ github.event.inputs.browser }}" == "chromium" ]; then
            sudo docker-compose run chrome-tests /bin/sh -c "allure generate allure-results --clean -o allure-report/chromium"
          elif [ "${{ github.event.inputs.browser }}" == "webkit" ]; then
            sudo docker-compose run webkit-tests /bin/sh -c "allure generate allure-results --clean -o allure-report/webkit"
          elif [ "${{ github.event.inputs.browser }}" == "firefox" ]; then
            sudo docker-compose run firefox-tests /bin/sh -c "allure generate allure-results --clean -o allure-report/firefox"
          fi

      - name: Update Allure history
        run: |
          if [ "${{ github.event.inputs.browser }}" == "chromium" ]; then
            sudo mkdir -p ./.github/chrome_reports/history
            sudo cp -R allure-report/chromium/history/* ./.github/chrome_reports/history/
          elif [ "${{ github.event.inputs.browser }}" == "webkit" ]; then
            sudo cp -R allure-report/webkit/history/* ./.github/webkit_reports/history/
          elif [ "${{ github.event.inputs.browser }}" == "firefox" ]; then
            sudo cp -R allure-report/firefox/history/* ./.github/firefox_reports/history/
          fi

      - name: Deploy Chrome report to GitHub Pages
        if: ${{ github.event.inputs.browser == 'chromium' }}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: chrome_reports
          folder: allure-report/chromium
          clean: true

      - name: Deploy Webkit report to GitHub Pages
        if: ${{ github.event.inputs.browser == 'webkit' }}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: webkit_reports
          folder: allure-report/webkit
          clean: true

      - name: Deploy Firefox report to GitHub Pages
        if: ${{ github.event.inputs.browser == 'firefox' }}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: firefox_reports
          folder: allure-report/firefox
          clean: true

      - name: Send notification to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ "${{ github.event.inputs.browser }}" == "chromium" ]; then
            REPORT_URL="https://bohdan-wtl.github.io/qr-generator/chrome_reports/"
          elif [ "${{ github.event.inputs.browser }}" == "webkit" ]; then
            REPORT_URL="https://bohdan-wtl.github.io/qr-generator/webkit_reports/"
          elif [ "${{ github.event.inputs.browser }}" == "firefox" ]; then
            REPORT_URL="https://bohdan-wtl.github.io/qr-generator/firefox_reports/"
          fi
          
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Tests results for browser: '"${{ github.event.inputs.browser }}"'",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":white_check_mark: Tests are finished for: *'"${{ github.event.inputs.browser }}"'*. Report link: <'"${REPORT_URL}"'|Open>"
                }
              }
            ]
          }' $SLACK_WEBHOOK_URL
