name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 180
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Update apt-get
        run: sudo apt-get update

#      - name: Install xvfb
#        run: sudo apt-get install -y xvfb

      - name: Install wget
        run: sudo apt-get install -y wget

      - name: Install default-jre
        run: sudo apt-get install -y default-jre

      - name: Download Allure
        run: wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz

      - name: Extract Allure
        run: tar -zxvf allure-2.25.0.tgz -C /opt/

      - name: Create a symbolic link
        run: sudo ln -s /opt/allure-2.25.0/bin/allure /usr/local/bin/allure

      - name: Run Playwright tests
        env:
          STAGE_URL: ${{ secrets.STAGE_URL }}
          STAGE_ADMIN_LINK: ${{ secrets.STAGE_ADMIN_LINK }}
          STAGE_ADMIN_EMAIL: ${{ secrets.STAGE_ADMIN_EMAIL }}
          STAGE_ADMIN_PASSWORD: ${{ secrets.STAGE_ADMIN_PASSWORD }}
        run: pytest tests/test_debug.py -s -v --alluredir=allure-results

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.ADMIN_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
