name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 180
    runs-on: ubuntu-latest

    env:
      STAGE_ADMIN_LINK: ${{ secrets.STAGE_ADMIN_LINK }}
      STAGE_ADMIN_EMAIL: ${{ secrets.STAGE_ADMIN_EMAIL }}
      STAGE_ADMIN_PASSWORD: ${{ secrets.STAGE_ADMIN_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Install wget
        run: sudo apt-get install -y wget

      - name: Install default-jre
        run: sudo apt-get install -y default-jre

      - name: Download Allure
        run: wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz

      - name: Extract Allure
        run: tar -zxvf allure-2.25.0.tgz -C /opt/

      - name: Create a symbolic link
        run: ln -s /opt/allure-2.25.0/bin/allure /usr/bin/allure

      - name: Run Playwright tests with Xvfb
        run: xvfb-run -a pytest

      - name: Generate Allure Report
        run: allure generate -c allure-results -o reports

      - name: Upload Allure Reports
        uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: allure-reports
          path: reports

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./reports
          destination_dir: allure-report
