name: Docker UI Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Select browser"
        required: true
        default: "chrome"
        type: choice
        options:
          - "chrome"
          - "webkit"
          - "firefox"

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      STAGE_ADMIN_LINK: ${{ secrets.STAGE_ADMIN_LINK }}
      STAGE_ADMIN_EMAIL: ${{ secrets.STAGE_ADMIN_EMAIL }}
      STAGE_ADMIN_PASSWORD: ${{ secrets.STAGE_ADMIN_PASSWORD }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.browser }}_reports
          path: ./.github/${{ github.event.inputs.browser }}_reports

      - name: Debug current directory
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls -la


      - name: Set up Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/.docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/bohdan-wtl/qr-generator/ui-tests:v1
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.CI_TOKEN }}


      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.browser }}" == "chrome" ]; then
            docker-compose up chrome-tests || true
          elif [ "${{ github.event.inputs.browser }}" == "webkit" ]; then
            docker-compose up webkit-tests || true
          elif [ "${{ github.event.inputs.browser }}" == "firefox" ]; then
            docker-compose up firefox-tests || true
          fi

#      - name: Copy history for Allure
#        run: |
#          sudo mkdir -p allure-results/history
#          cp -R allure-report/history/* allure-results/history/
          

      - name: Setup Pages
        uses: actions/configure-pages@v5


      - name: Generate Allure report
        run: |
          if [ "${{ github.event.inputs.browser }}" == "chrome" ]; then
            sudo docker-compose run chrome-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"
          elif [ "${{ github.event.inputs.browser }}" == "webkit" ]; then
            sudo docker-compose run webkit-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"
          elif [ "${{ github.event.inputs.browser }}" == "firefox" ]; then
            sudo docker-compose run firefox-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"
          fi

  deploy-report:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: tests
    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: ${{ github.event.inputs.browser }}_reports
          folder: .
          clean: true

      - name: Send notification to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          REPORT_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.inputs.browser }}_reports"
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Tests results for browser: '"${{ github.event.inputs.browser }}"'",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":white_check_mark: Tests are finished for: *'"${{ github.event.inputs.browser }}"'*. Report link: <'"${REPORT_URL}"'|Open>"
                }
              }
            ]
          }' $SLACK_WEBHOOK_URL
