name: Docker UI Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Select browser"
        required: true
        default: "chrome"
        type: choice
        options:
          - "chrome"
          - "webkit"
          - "firefox"

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      STAGE_ADMIN_LINK: ${{ secrets.STAGE_ADMIN_LINK }}
      STAGE_ADMIN_EMAIL: ${{ secrets.STAGE_ADMIN_EMAIL }}
      STAGE_ADMIN_PASSWORD: ${{ secrets.STAGE_ADMIN_PASSWORD }}
    steps:

      # Чекаут основной ветки main для запуска тестов
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Установка Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Запуск тестов для указанного браузера
      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.browser }}" == "chrome" ]; then
            docker-compose up chrome-tests || true
          elif [ "${{ github.event.inputs.browser }}" == "webkit" ]; then
            docker-compose up webkit-tests || true
          elif [ "${{ github.event.inputs.browser }}" == "firefox" ]; then
            docker-compose up firefox-tests || true
          fi

      # Генерация Allure отчёта
      - name: Generate Allure report
        run: |
          sudo docker-compose run ${{ github.event.inputs.browser }}-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Debug current directory and files
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of current directory:"
          ls -la

      # Копирование отчёта Allure в подкаталог браузера
#      - name: Copy Allure report to subdirectory
#        run: |
#          mkdir -p ./gh-pages/${{ github.event.inputs.browser }}_reports
#          cp -R allure-report/* ./gh-pages/${{ github.event.inputs.browser }}_reports/

      # Деплой отчётов в ветку gh-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: ./gh-pages/${{ github.event.inputs.browser }}
          clean: false

      - name: Debug current directory and files
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of current directory:"
          ls -la
