name: UI Tests

on:
  workflow_dispatch:
    inputs:
      browsers:
        description: "Select browser"
        required: true
        default: "chromium"
        type: choice
        options:
          - "chromium"
          - "webkit"
          - "firefox"

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      BROWSER: ${{ github.event.inputs.browser }}
      STAGE_ADMIN_LINK: ${{ secrets.STAGE_ADMIN_LINK }}
      STAGE_ADMIN_EMAIL: ${{ secrets.STAGE_ADMIN_EMAIL }}
      STAGE_ADMIN_PASSWORD: ${{ secrets.STAGE_ADMIN_PASSWORD }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check out gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run Chrome tests
        if: ${{ env.BROWSER == 'chromium' }}
        env:
          BROWSER: "chromium"
        run: docker-compose up --exit-code-from chrome-tests || true

      - name: Run Webkit tests
        if: ${{ env.BROWSER == 'webkit' }}
        env:
          BROWSER: "webkit"
        run: docker-compose up --exit-code-from webkit-tests || true

      - name: Run Firefox tests
        if: ${{ env.BROWSER == 'firefox' }}
        env:
          BROWSER: "firefox"
        run: docker-compose up --exit-code-from firefox-tests || true

      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history
          sudo cp -R ./.github/gh-pages/history/* allure-results/history/

      - name: Generate Allure report
        run: |
          if [ "$BROWSER" == "chromium" ]; then
            sudo docker-compose run --rm chrome-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"
          elif [ "$BROWSER" == "webkit" ]; then
            sudo docker-compose run --rm webkit-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"
          elif [ "$BROWSER" == "firefox" ]; then
            sudo docker-compose run --rm firefox-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"
          else
            echo "Invalid browser selected: $BROWSER"
          fi


      - name: Update Allure history
        run: |
          sudo cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
