name: Regression Tests
on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Select browser"
        required: true
        default: "chrome"
        type: choice
        options:
          - "chrome"
          - "webkit"
          - "firefox"

jobs:
  tests_and_deploy:
    runs-on: ubuntu-latest
    env:
      STAGE_ADMIN_LINK: ${{ secrets.STAGE_ADMIN_LINK }}
      STAGE_ADMIN_EMAIL: ${{ secrets.STAGE_ADMIN_EMAIL }}
      STAGE_ADMIN_PASSWORD: ${{ secrets.STAGE_ADMIN_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./gh-pages
          clean: true

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CI_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Install Docker Compose
        run: |
          sudo apt-get update -y
          sudo apt-get install -y docker-compose

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.browser }}" == "chrome" ]; then
            docker-compose up chrome-tests || true
          elif [ "${{ github.event.inputs.browser }}" == "webkit" ]; then
            docker-compose up webkit-tests || true
          elif [ "${{ github.event.inputs.browser }}" == "firefox" ]; then
            docker-compose up firefox-tests || true
          fi

      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history
          sudo cp -R ./gh-pages/${{ github.event.inputs.browser }}/history/* allure-results/history/

      - name: Generate Allure report
        run: |
          docker-compose run ${{ github.event.inputs.browser }}-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Create directory for browser reports
        run: |
          mkdir -p ./gh-pages/${{ github.event.inputs.browser }}
          echo "Created directory: ./gh-pages/${{ github.event.inputs.browser }}"

      - name: Copy Allure report to browser directory
        run: |
          cp -R allure-report/* ./gh-pages/${{ github.event.inputs.browser }}/
          echo "Copied Allure report to ./gh-pages/${{ github.event.inputs.browser }}"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: ./gh-pages/${{ github.event.inputs.browser }}
          target-folder: ./${{ github.event.inputs.browser }}
          clean: true

      - name: Send notification to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
            if [ "${{ github.event.inputs.browser }}" = "chrome" ]; then
              REPORT_URL="https://chrome-pi.vercel.app"
            elif [ "${{ github.event.inputs.browser }}" = "firefox" ]; then
              REPORT_URL="https://firefox-kohl.vercel.app"
            elif [ "${{ github.event.inputs.browser }}" = "webkit" ]; then
              REPORT_URL="https://webkit-two.vercel.app"
            fi
          
            curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Tests are finished",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":white_check_mark: @here Tests are finished for *'"${{ github.event.inputs.browser }}"'*. <'"${REPORT_URL}"'|Open link>"
                }
              }
            ]
            }' $SLACK_WEBHOOK_URL
