name: UI Tests

on:
  workflow_dispatch:
    inputs:
      browsers:
        description: "Select browser"
        required: true
        default: "chrome"
        type: choice
        options:
          - "chrome"
          - "webkit"
          - "firefox"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check out gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run Chrome tests
        if: ${{ github.event.inputs.browser == 'chrome' }}
        env:
          BROWSER: "chromium"
          STAGE_ADMIN_LINK: ${{ secrets.STAGE_ADMIN_LINK }}
          STAGE_ADMIN_EMAIL: ${{ secrets.STAGE_ADMIN_EMAIL }}
          STAGE_ADMIN_PASSWORD: ${{ secrets.STAGE_ADMIN_PASSWORD }}
        run: docker-compose up chrome-tests --exit-code-from regression || true

      - name: Run Webkit tests
        if: ${{ github.event.inputs.browser == 'webkit' }}
        env:
          BROWSER: "webkit"
          STAGE_ADMIN_LINK: ${{ secrets.STAGE_ADMIN_LINK }}
          STAGE_ADMIN_EMAIL: ${{ secrets.STAGE_ADMIN_EMAIL }}
          STAGE_ADMIN_PASSWORD: ${{ secrets.STAGE_ADMIN_PASSWORD }}
        run: docker-compose up webkit-tests --exit-code-from regression || true

      - name: Run Firefox tests
        if: ${{ github.event.inputs.browser == 'firefox' }}
        env:
          BROWSER: "firefox"
          STAGE_ADMIN_LINK: ${{ secrets.STAGE_ADMIN_LINK }}
          STAGE_ADMIN_EMAIL: ${{ secrets.STAGE_ADMIN_EMAIL }}
          STAGE_ADMIN_PASSWORD: ${{ secrets.STAGE_ADMIN_PASSWORD }}
        run: docker-compose up firefox-tests --exit-code-from regression || true

      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history
          sudo cp -R ./.github/gh-pages/history/* allure-results/history/

      - name: Generate Allure report
        run: |
          if [ "${{ github.event.inputs.browser }}" == "chrome" ]; then
            sudo docker-compose run --rm chrome-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"
          elif [ "${{ github.event.inputs.browser }}" == "webkit" ]; then
            sudo docker-compose run --rm webkit-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"
          elif [ "${{ github.event.inputs.browser }}" == "firefox" ]; then
            sudo docker-compose run --rm firefox-tests /bin/sh -c "allure generate allure-results --clean -o allure-report"
          else
            echo "Invalid browser selected: ${{ github.event.inputs.browser }}"
          fi


      - name: Update Allure history
        run: |
          sudo cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
